coursier.ResolutionException: Exception during resolution
Caused by: java.io.FileNotFoundException: C:\Users\ruslan.aghalarov\Drive - Personal\Drive - Personal\scala\patmat\null\Coursier\cache\v1\.structure.lock (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at coursier.CachePath.withStructureLock(CachePath.java:112)
	at coursier.Cache$.coursier$Cache$$withStructureLock(Cache.scala:80)
	at coursier.Cache$.coursier$Cache$$withLockOr(Cache.scala:94)
	at coursier.Cache$$anonfun$remote$1$1.apply(Cache.scala:674)
	at coursier.Cache$$anonfun$remote$1$1.apply(Cache.scala:556)
	at scalaz.concurrent.Task$.Try(Task.scala:456)
	at scalaz.concurrent.Task$$anonfun$apply$25.apply(Task.scala:353)
	at scalaz.concurrent.Task$$anonfun$apply$25.apply(Task.scala:353)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:coursierResolutions) coursier.ResolutionException: Exception during resolution
